# Generated by Django 4.2.13 on 2025-10-08 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0053_alter_sponsorship_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(help_text='Tên công khai của nhà tài trợ.', max_length=200, verbose_name='Tên thương hiệu')),
                ('tagline', models.CharField(blank=True, help_text='Một câu giới thiệu ngắn gọn.', max_length=255, verbose_name='Slogan/Khẩu hiệu')),
                ('description', models.TextField(blank=True, help_text='Mô tả về thương hiệu, lĩnh vực hoạt động...', verbose_name='Giới thiệu chi tiết')),
                ('website_url', models.URLField(blank=True, verbose_name='Link trang web')),
                ('cover_image', models.ImageField(blank=True, help_text='Ảnh bìa cho trang hồ sơ.', null=True, upload_to='sponsor_covers/', verbose_name='Ảnh bìa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản Nhà tài trợ')),
            ],
            options={
                'verbose_name': 'Hồ sơ Nhà tài trợ',
                'verbose_name_plural': 'Các Hồ sơ Nhà tài trợ',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Nội dung nhận xét')),
                ('is_approved', models.BooleanField(default=False, help_text='Nhà tài trợ có thể chọn ẩn/hiện nhận xét này trên hồ sơ của họ.', verbose_name='Được hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người viết')),
                ('sponsor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='sponsors.sponsorprofile', verbose_name='Hồ sơ Nhà tài trợ')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament', verbose_name='Giải đấu liên quan')),
            ],
            options={
                'verbose_name': 'Nhận xét',
                'verbose_name_plural': 'Các Nhận xét',
                'ordering': ['-created_at'],
            },
        ),
    ]
