# Generated by Django 4.2.13 on 2025-10-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_testimonial_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Nhà tài trợ có thể chọn ẩn/hiện nhận xét này trên hồ sơ của họ.', verbose_name='Được hiển thị'),
        ),
    ]
