# Generated by Django 4.2.13 on 2025-10-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_alter_testimonial_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại'),
        ),
    ]
