# Generated by Django 4.2.13 on 2025-10-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_sponsorprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorprofile',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='sponsor_logos/', verbose_name='Logo thương hiệu'),
        ),
    ]
