# Generated by Django 4.2.13 on 2025-10-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0005_sponsorprofile_brand_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorprofile',
            name='cover_image',
        ),
    ]
