# Generated by Django 4.2.13 on 2025-10-14 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_sponsorprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sponsors', '0006_remove_sponsorprofile_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldSponsorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='sponsor_logos/')),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='old_sponsor_profile_temp', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản Nhà tài trợ')),
            ],
            options={
                'db_table': 'sponsors_sponsorprofile',
            },
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='sponsor_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='users.sponsorprofile', verbose_name='Hồ sơ Nhà tài trợ'),
        ),
        migrations.DeleteModel(
            name='SponsorProfile',
        ),
    ]
