# Generated by Django 4.2.13 on 2025-10-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0007_oldsponsorprofile_alter_testimonial_sponsor_profile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldSponsorProfile',
        ),
    ]
