# Generated by Django 4.2.13 on 2025-09-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xét duyệt'), ('ACTIVE', 'Đang hoạt động'), ('REJECTED', 'Bị từ chối'), ('DISABLED', 'Vô hiệu hóa')], default='PENDING', max_length=10, verbose_name='Trạng thái'),
        ),
    ]
