# Generated by Django 4.2.13 on 2025-09-30 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_role_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0033_tournamentstaff'),
        ('organizations', '0002_organization_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề công việc')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('budget', models.CharField(blank=True, help_text="Ví dụ: 500.000 VNĐ/trận, hoặc 'Thỏa thuận'", max_length=150, verbose_name='Mức kinh phí')),
                ('status', models.CharField(choices=[('OPEN', 'Đang mở'), ('CLOSED', 'Đã đóng')], default='OPEN', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role_required', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role', verbose_name='Vai trò cần tuyển')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='tournaments.tournament', verbose_name='Giải đấu')),
            ],
            options={
                'verbose_name': 'Tin Tuyển dụng',
                'verbose_name_plural': 'Các Tin Tuyển dụng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Gửi một vài lời giới thiệu về kỹ năng và kinh nghiệm của bạn cho BTC.', verbose_name='Lời nhắn (tùy chọn)')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ'), ('APPROVED', 'Đã chấp thuận'), ('REJECTED', 'Đã từ chối')], default='PENDING', max_length=10, verbose_name='Trạng thái')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL, verbose_name='Người ứng tuyển')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='organizations.jobposting', verbose_name='Công việc')),
            ],
            options={
                'verbose_name': 'Đơn Ứng tuyển',
                'verbose_name_plural': 'Các Đơn Ứng tuyển',
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'applicant')},
            },
        ),
    ]
