# Generated by Django 4.2.13 on 2025-10-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_jobposting_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='location_detail',
            field=models.CharField(blank=True, help_text='Nếu bỏ trống, sẽ lấy theo địa điểm của giải đấu.', max_length=100, verbose_name='Tỉnh/Thành phố (tùy chọn)'),
        ),
    ]
