# Generated by Django 4.2.13 on 2025-10-01 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0004_jobposting_location_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], verbose_name='Số sao')),
                ('comment', models.TextField(blank=True, verbose_name='Nội dung nhận xét')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='organizations.jobapplication', verbose_name='Đơn ứng tuyển')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người được đánh giá (Chuyên gia)')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá (BTC)')),
            ],
            options={
                'verbose_name': 'Đánh giá Chuyên gia',
                'verbose_name_plural': 'Các Đánh giá Chuyên gia',
                'ordering': ['-created_at'],
            },
        ),
    ]
