# Generated by Django 4.2.13 on 2025-10-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_professionalreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email liên hệ'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại'),
        ),
    ]
