# Generated by Django 4.2.13 on 2025-10-13 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0063_team_coach_alter_team_coach_name_and_more'),
        ('users', '0019_alter_role_id_stadiumprofile_coachprofile'),
        ('organizations', '0006_organization_contact_email_organization_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='posted_by',
            field=models.CharField(choices=[('TOURNAMENT', 'Ban Tổ chức Giải đấu'), ('STADIUM', 'Sân bóng')], default='TOURNAMENT', max_length=20, verbose_name='Đăng bởi'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='stadium',
            field=models.ForeignKey(blank=True, help_text='Chỉ điền nếu tin này được đăng bởi Sân bóng', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='users.stadiumprofile', verbose_name='Sân bóng'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location_detail',
            field=models.CharField(blank=True, help_text='Nếu bỏ trống, sẽ lấy theo địa điểm của giải đấu hoặc sân bóng.', max_length=100, verbose_name='Tỉnh/Thành phố (tùy chọn)'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='tournament',
            field=models.ForeignKey(blank=True, help_text='Chỉ điền nếu tin này được đăng bởi BTC', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='tournaments.tournament', verbose_name='Giải đấu'),
        ),
    ]
