# Generated by Django 4.2.13 on 2025-10-14 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0007_jobposting_posted_by_jobposting_stadium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='professional_user',
            field=models.ForeignKey(blank=True, help_text='Chỉ điền nếu tin này được đăng bởi Chuyên gia tìm việc', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_job_postings', to=settings.AUTH_USER_MODEL, verbose_name='Chuyên gia'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='posted_by',
            field=models.CharField(choices=[('TOURNAMENT', 'Ban Tổ chức Giải đấu'), ('STADIUM', 'Sân bóng'), ('PROFESSIONAL', 'Chuyên gia tìm việc')], default='TOURNAMENT', max_length=20, verbose_name='Đăng bởi'),
        ),
    ]
