# Generated by Django 4.2.13 on 2025-10-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_jobposting_professional_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the name', null=True, unique=True, verbose_name='Slug'),
        ),
    ]
