# Generated by Django 4.2.13 on 2025-10-16 13:18

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    
    for org in Organization.objects.all():
        if not org.slug:
            base_slug = slugify(org.name)
            slug = base_slug
            counter = 1
            
            # Đảm bảo slug là unique
            while Organization.objects.filter(slug=slug).exclude(pk=org.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            org.slug = slug
            org.save()


def reverse_populate_slugs(apps, schema_editor):
    # Không cần làm gì khi rollback
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_organization_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
