# Generated by Django 4.2.13 on 2025-10-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_auto_20251016_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the name', unique=True, verbose_name='Slug'),
        ),
    ]
