# Generated by Django 4.2.13 on 2025-10-24 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Địa chỉ email để nhận thông báo', max_length=254, unique=True, verbose_name='Email đăng ký')),
                ('is_active', models.BooleanField(default=True, help_text='Có nhận thông báo hay không', verbose_name='Trạng thái hoạt động')),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đăng ký')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hủy đăng ký')),
            ],
            options={
                'verbose_name': 'Đăng ký nhận thông báo',
                'verbose_name_plural': 'Đăng ký nhận thông báo',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
