# Generated by Django 4.2.13 on 2025-10-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề chính')),
                ('subtitle', models.TextField(verbose_name='Tiêu đề phụ')),
                ('badge_text', models.CharField(max_length=100, verbose_name='Text badge')),
                ('button_text', models.CharField(max_length=50, verbose_name='Text nút')),
                ('button_url', models.CharField(default="{% url 'shop:product_list' %}", max_length=200, verbose_name='URL nút')),
                ('main_image', models.ImageField(upload_to='shop/banners/', verbose_name='Hình ảnh chính')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner Shop',
                'verbose_name_plural': 'Banner Shop',
                'ordering': ['-created_at'],
            },
        ),
    ]
