# Generated by Django 4.2.13 on 2025-10-11 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopbanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopbanner',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Banner Shop', 'verbose_name_plural': 'Banner Shop'},
        ),
        migrations.AddField(
            model_name='shopbanner',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Thứ tự'),
        ),
        migrations.AddField(
            model_name='shopbanner',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Sản phẩm liên kết'),
        ),
    ]
