# Generated by Django 4.2.13 on 2025-10-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shopbanner_options_shopbanner_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbanner',
            name='button_url',
            field=models.CharField(default='/shop/products/', max_length=200, verbose_name='URL nút'),
        ),
    ]
