# Generated by Django 4.2.13 on 2025-10-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_fix_banner_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(verbose_name='URL nguồn')),
                ('source_name', models.CharField(blank=True, max_length=100, verbose_name='Tên nguồn')),
                ('crawled_name', models.CharField(blank=True, max_length=200, verbose_name='Tên sản phẩm')),
                ('crawled_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Giá')),
                ('crawled_description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('crawled_image_url', models.URLField(blank=True, verbose_name='URL hình ảnh')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('error_message', models.TextField(blank=True, verbose_name='Thông báo lỗi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xử lý')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Import Sản phẩm',
                'verbose_name_plural': 'Import Sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
    ]
