# Generated by Django 4.2.13 on 2025-10-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_cartitem_unique_together_cartitem_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_imported',
            field=models.BooleanField(default=False, verbose_name='Sản phẩm import'),
        ),
        migrations.AddField(
            model_name='product',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link gốc'),
        ),
    ]
