# Generated by Django 4.2.13 on 2025-10-11 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_is_imported_product_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('phone', 'Điện thoại'), ('email', 'Email'), ('messenger', 'Facebook Messenger'), ('zalo', 'Zalo'), ('other', 'Khác')], max_length=20, verbose_name='Loại liên hệ')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('value', models.CharField(max_length=200, verbose_name='Giá trị')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Mô tả')),
                ('icon', models.CharField(default='fas fa-phone', max_length=50, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thông tin liên hệ',
                'verbose_name_plural': 'Thông tin liên hệ',
                'ordering': ['order', 'contact_type'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên phương thức')),
                ('payment_type', models.CharField(choices=[('bank_transfer', 'Chuyển khoản ngân hàng'), ('e_wallet', 'Ví điện tử'), ('cod', 'Thanh toán khi nhận hàng')], max_length=20, verbose_name='Loại thanh toán')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('icon', models.CharField(default='fas fa-credit-card', max_length=50, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Phương thức thanh toán',
                'verbose_name_plural': 'Phương thức thanh toán',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('policy_type', models.CharField(choices=[('warning', 'Lưu ý quan trọng'), ('success', 'Chính sách đổi trả'), ('info', 'Thông tin khác')], max_length=20, verbose_name='Loại chính sách')),
                ('icon', models.CharField(default='fas fa-info-circle', max_length=50, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chính sách thanh toán',
                'verbose_name_plural': 'Chính sách thanh toán',
                'ordering': ['order', 'policy_type'],
            },
        ),
        migrations.CreateModel(
            name='PaymentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bước thanh toán',
                'verbose_name_plural': 'Bước thanh toán',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EWalletAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(max_length=100, verbose_name='Tên ví')),
                ('account_info', models.CharField(max_length=200, verbose_name='Thông tin tài khoản')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='shop/qr_codes/', verbose_name='QR Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ewallet_accounts', to='shop.paymentmethod', verbose_name='Phương thức thanh toán')),
            ],
            options={
                'verbose_name': 'Tài khoản ví điện tử',
                'verbose_name_plural': 'Tài khoản ví điện tử',
                'ordering': ['order', 'wallet_name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Tên ngân hàng')),
                ('account_holder', models.CharField(max_length=100, verbose_name='Chủ tài khoản')),
                ('account_number', models.CharField(max_length=50, verbose_name='Số tài khoản')),
                ('branch', models.CharField(blank=True, max_length=100, verbose_name='Chi nhánh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='shop.paymentmethod', verbose_name='Phương thức thanh toán')),
            ],
            options={
                'verbose_name': 'Tài khoản ngân hàng',
                'verbose_name_plural': 'Tài khoản ngân hàng',
                'ordering': ['order', 'bank_name'],
            },
        ),
    ]
