# Generated by Django 4.2.13 on 2025-10-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_contactinfo_paymentmethod_paymentpolicy_paymentstep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='shop/qr_codes/', verbose_name='QR Code'),
        ),
    ]
