# Generated by Django 4.2.13 on 2025-10-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_bankaccount_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='shop/payment_proofs/', verbose_name='Hóa đơn chuyển khoản'),
        ),
    ]
