# Generated by Django 4.2.13 on 2025-10-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng (COD)'), ('bank_transfer', 'Chuyển khoản ngân hàng'), ('e_wallet', 'Ví điện tử')], default='cod', max_length=20, verbose_name='Phương thức thanh toán'),
        ),
    ]
