# Generated by Django 4.2.13 on 2025-10-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_customershippinginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Ví dụ: 0123456789', max_length=20, verbose_name='Số điện thoại')),
                ('zalo_link', models.CharField(help_text='Ví dụ: https://zalo.me/0123456789', max_length=200, verbose_name='Link Zalo')),
                ('messenger_link', models.CharField(help_text='Ví dụ: https://m.me/dbpsports', max_length=200, verbose_name='Link Messenger')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt popup liên hệ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Cài đặt liên hệ',
                'verbose_name_plural': 'Cài đặt liên hệ',
            },
        ),
    ]
