# Generated by Django 4.2.13 on 2025-10-15 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_contactsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Giá nhập vào để tính lãi', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá vốn'),
        ),
    ]
