# Generated by Django 4.2.13 on 2025-10-16 13:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_jobposting_professional_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0016_product_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giỏ hàng Shop BTC',
                'verbose_name_plural': 'Giỏ hàng Shop BTC',
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='org_shop/categories/', verbose_name='Hình ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_categories', to='organizations.organization', verbose_name='Ban tổ chức')),
            ],
            options={
                'verbose_name': 'Danh mục Shop BTC',
                'verbose_name_plural': 'Danh mục Shop BTC',
                'ordering': ['name'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Mã đơn hàng')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('shipping_address', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='Thành phố')),
                ('shipping_district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Tổng tiền hàng')),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Phí vận chuyển')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Tổng cộng')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('shipped', 'Đã gửi hàng'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái đơn hàng')),
                ('payment_status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('failed', 'Thanh toán thất bại'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('payment_method', models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng (COD)'), ('bank_transfer', 'Chuyển khoản ngân hàng'), ('e_wallet', 'Ví điện tử')], default='cod', max_length=20, verbose_name='Phương thức thanh toán')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='org_shop/payment_proofs/', verbose_name='Hóa đơn chuyển khoản')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to='organizations.organization', verbose_name='Ban tổ chức')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đơn hàng Shop BTC',
                'verbose_name_plural': 'Đơn hàng Shop BTC',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('short_description', models.TextField(blank=True, max_length=300, verbose_name='Mô tả ngắn')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá khuyến mãi')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=0, help_text='Giá nhập vào để tính lãi', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá vốn')),
                ('sku', models.CharField(max_length=50, verbose_name='Mã sản phẩm')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Trọng lượng (kg)')),
                ('has_sizes', models.BooleanField(default=False, verbose_name='Có nhiều size')),
                ('main_image', models.ImageField(upload_to='org_shop/products/', verbose_name='Hình ảnh chính')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Link gốc')),
                ('is_imported', models.BooleanField(default=False, verbose_name='Sản phẩm import')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('published', 'Đã xuất bản'), ('out_of_stock', 'Hết hàng'), ('discontinued', 'Ngừng bán')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Sản phẩm nổi bật')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Bán chạy')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xuất bản')),
                ('available_sizes', models.ManyToManyField(blank=True, to='shop.productsize', verbose_name='Size có sẵn')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.organizationcategory', verbose_name='Danh mục')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='organizations.organization', verbose_name='Ban tổ chức')),
            ],
            options={
                'verbose_name': 'Sản phẩm Shop BTC',
                'verbose_name_plural': 'Sản phẩm Shop BTC',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(help_text='Tên hiển thị của shop', max_length=200, verbose_name='Tên shop')),
                ('shop_description', models.TextField(blank=True, verbose_name='Mô tả shop')),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='org_shop/logos/', verbose_name='Logo shop')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Tên ngân hàng')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='Số tài khoản')),
                ('bank_account_name', models.CharField(blank=True, max_length=100, verbose_name='Tên chủ tài khoản')),
                ('payment_qr_code', models.ImageField(blank=True, null=True, upload_to='org_shop/qr_codes/', verbose_name='QR Code thanh toán')),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Phí vận chuyển mặc định')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Ngưỡng miễn phí ship')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt shop')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_settings', to='organizations.organization', verbose_name='Ban tổ chức')),
            ],
            options={
                'verbose_name': 'Cài đặt Shop BTC',
                'verbose_name_plural': 'Cài đặt Shop BTC',
            },
        ),
        migrations.CreateModel(
            name='OrganizationProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='org_shop/products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.organizationproduct')),
            ],
            options={
                'verbose_name': 'Hình ảnh sản phẩm Shop BTC',
                'verbose_name_plural': 'Hình ảnh sản phẩm Shop BTC',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá tại thời điểm đặt hàng')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.organizationorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.organizationproduct')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong đơn hàng Shop BTC',
                'verbose_name_plural': 'Sản phẩm trong đơn hàng Shop BTC',
            },
        ),
        migrations.CreateModel(
            name='OrganizationProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, verbose_name='Mã SKU')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá riêng')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá khuyến mãi riêng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.organizationproduct', verbose_name='Sản phẩm')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productsize', verbose_name='Size')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm Shop BTC',
                'verbose_name_plural': 'Biến thể sản phẩm Shop BTC',
                'ordering': ['product', 'size__order', 'size__name'],
                'unique_together': {('product', 'size')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.organizationcart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.organizationproduct')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productsize', verbose_name='Size')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong giỏ Shop BTC',
                'verbose_name_plural': 'Sản phẩm trong giỏ Shop BTC',
                'unique_together': {('cart', 'product', 'size')},
            },
        ),
    ]
