# Generated by Django 4.2.13 on 2025-10-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_organizationcart_organizationcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationshopsettings',
            name='shop_banner',
            field=models.ImageField(blank=True, help_text='Banner hiển thị trên đầu trang shop', null=True, upload_to='org_shop/banners/', verbose_name='Banner shop'),
        ),
    ]
