# Generated by Django 4.2.13 on 2025-10-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_organizationorder_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationshopsettings',
            name='shop_lock_reason',
            field=models.TextField(blank=True, help_text='Ghi chú từ Admin về lý do khoá shop', verbose_name='Lý do khoá shop'),
        ),
        migrations.AddField(
            model_name='organizationshopsettings',
            name='shop_locked',
            field=models.BooleanField(default=True, help_text='Shop BTC bị khoá mặc định và cần Admin phê duyệt để mở', verbose_name='Khoá Shop BTC'),
        ),
        migrations.AddField(
            model_name='organizationshopsettings',
            name='shop_unlock_request_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày yêu cầu mở khoá'),
        ),
        migrations.AddField(
            model_name='organizationshopsettings',
            name='shop_unlock_request_message',
            field=models.TextField(blank=True, help_text='Lời nhắn từ BTC khi yêu cầu mở khoá shop', verbose_name='Lời nhắn từ BTC'),
        ),
        migrations.AddField(
            model_name='organizationshopsettings',
            name='shop_unlock_requested',
            field=models.BooleanField(default=False, help_text='BTC đã gửi yêu cầu mở khoá shop', verbose_name='BTC đã yêu cầu mở khoá'),
        ),
    ]
