# Generated by Django 4.2.13 on 2025-09-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tên chủ tài khoản'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Số tài khoản'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tên ngân hàng'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='payment_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Ảnh mã QR'),
        ),
    ]
