# Generated by Django 4.2.13 on 2025-09-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='rules',
            field=models.TextField(blank=True, help_text='Nhập các điều lệ, quy định hoặc thông báo của giải đấu tại đây. Bạn có thể sử dụng mã HTML cơ bản để định dạng.', verbose_name='Điều lệ & Thông báo'),
        ),
    ]
