# Generated by Django 4.2.13 on 2025-09-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('PUBLIC', 'Gửi cho Mọi người (Cầu thủ & Đội trưởng)'), ('CAPTAINS_ONLY', 'Chỉ gửi cho Đội trưởng')], default='PUBLIC', help_text='Chọn nhóm người dùng sẽ thấy thông báo này.', max_length=15, verbose_name='Đối tượng'),
        ),
    ]
