# Generated by Django 5.2.5 on 2025-08-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('REGISTRATION_OPEN', 'Đang mở đăng ký'), ('IN_PROGRESS', 'Đang diễn ra'), ('FINISHED', 'Đã kết thúc')], default='REGISTRATION_OPEN', max_length=20),
        ),
    ]
