# Generated by Django 4.2.13 on 2025-09-20 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0006_announcement_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Đã đọc bởi'),
        ),
    ]
