# Generated by Django 4.2.13 on 2025-09-21 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tournaments', '0007_announcement_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='organizations.organization', verbose_name='Đơn vị tổ chức'),
        ),
    ]
