# Generated by Django 4.2.13 on 2025-09-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_tournament_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='region',
            field=models.CharField(choices=[('MIEN_BAC', 'Miền Bắc'), ('MIEN_TRUNG', 'Miền Trung'), ('MIEN_NAM', 'Miền Nam'), ('KHAC', 'Khác')], default='KHAC', max_length=20, verbose_name='Khu vực'),
        ),
    ]
