# Generated by Django 5.2.5 on 2025-08-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_group_team_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_round',
            field=models.CharField(choices=[('GROUP', 'Vòng bảng'), ('QUARTER', 'Tứ kết'), ('SEMI', 'Bán kết'), ('FINAL', 'Chung kết')], default='GROUP', max_length=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tournament_banners/'),
        ),
    ]
