# Generated by Django 4.2.13 on 2025-09-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_tournament_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_round',
            field=models.CharField(choices=[('GROUP', 'Vòng bảng'), ('QUARTER', 'Tứ kết'), ('SEMI', 'Bán kết'), ('THIRD_PLACE', 'Tranh Hạng Ba'), ('FINAL', 'Chung kết')], default='GROUP', max_length=20),
        ),
    ]
