# Generated by Django 4.2.13 on 2025-09-21 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_alter_match_match_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tournament_photos/', verbose_name='Ảnh')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Chú thích')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tournaments.tournament', verbose_name='Giải đấu')),
            ],
            options={
                'verbose_name': 'Ảnh Giải đấu',
                'verbose_name_plural': 'Thư viện ảnh Giải đấu',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
