# Generated by Django 5.2.5 on 2025-08-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_team_payment_proof_team_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='livestream_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
