# Generated by Django 4.2.13 on 2025-09-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_tournamentphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='gallery_url',
            field=models.URLField(blank=True, help_text='Dán đường link chia sẻ của album ảnh Google Drive hoặc Google Photos tại đây.', max_length=500, null=True, verbose_name='Link Album Ảnh Gốc'),
        ),
    ]
