# Generated by Django 4.2.13 on 2025-09-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_tournament_gallery_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_penalty_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tỉ số penalty đội 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_penalty_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tỉ số penalty đội 2'),
        ),
    ]
