# Generated by Django 5.2.5 on 2025-08-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_match_livestream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='commentator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
