# Generated by Django 4.2.13 on 2025-09-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_match_team1_penalty_score_match_team2_penalty_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_own_goal',
            field=models.BooleanField(default=False, verbose_name='Bàn phản lưới?'),
        ),
    ]
