# Generated by Django 4.2.13 on 2025-09-24 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0014_goal_is_own_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Người theo dõi'),
        ),
    ]
