# Generated by Django 4.2.13 on 2025-09-24 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0015_tournament_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('notification_type', models.CharField(choices=[('MATCH_RESULT', 'Kết quả trận đấu'), ('NEW_TEAM', 'Đội mới đăng ký'), ('GENERIC', 'Thông báo chung')], default='GENERIC', max_length=20, verbose_name='Loại thông báo')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link liên quan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
