# Generated by Django 4.2.13 on 2025-09-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_notification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='tournaments_user_id_ecbef5_idx'),
        ),
    ]
