# Generated by Django 5.2.5 on 2025-08-30 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_alter_player_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(condition=models.Q(('minute__gte', 0), ('minute__lte', 150)), name='card_minute_range'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('minute__gte', 0), ('minute__lte', 150)), name='goal_minute_range'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='uniq_group_name_in_tournament'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('team', 'jersey_number'), name='uniq_jersey_per_team'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(condition=models.Q(('jersey_number__gte', 1), ('jersey_number__lte', 99)), name='jersey_between_1_99'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='uniq_team_name_in_tournament'),
        ),
    ]
