# Generated by Django 5.2.5 on 2025-09-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_homebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ticker_text',
            field=models.TextField(blank=True, help_text='Dùng ký tự • để ngăn cách các thông điệp', null=True),
        ),
    ]
