# Generated by Django 4.2.13 on 2025-09-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('captain', 'name'), name='unique_team_name_per_captain'),
        ),
    ]
