# Generated by Django 4.2.13 on 2025-09-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_team_unique_team_name_per_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Ảnh đại diện hiển thị cho trận đấu trong thư viện ảnh.', null=True, upload_to='match_covers/', verbose_name='Ảnh bìa trận đấu'),
        ),
        migrations.AddField(
            model_name='match',
            name='gallery_url',
            field=models.URLField(blank=True, help_text='Dán đường link album ảnh (Google Photos, Facebook,...) của riêng trận đấu này.', max_length=500, null=True, verbose_name='Link Album ảnh của trận đấu'),
        ),
    ]
