# Generated by Django 5.2.5 on 2025-09-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_match_ticker_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ticker_text',
            field=models.CharField(blank=True, default='', help_text='Dòng chữ chạy trên màn hình livestream. Nếu để trống, hệ thống sẽ dùng thông báo mặc định.', max_length=255),
            preserve_default=False,
        ),
    ]
