# Generated by Django 4.2.13 on 2025-09-27 12:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_match_cover_photo_match_gallery_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('CHAMPION', 'Vô địch'), ('RUNNER_UP', 'Á quân'), ('THIRD_PLACE', 'Hạng ba'), ('FAIR_PLAY', 'Giải Phong cách / Fair Play'), ('OTHER', 'Khác')], max_length=20, verbose_name='Loại danh hiệu')),
                ('description', models.CharField(blank=True, help_text="Ghi rõ hơn về danh hiệu, ví dụ: 'Vô địch mùa giải 2025'", max_length=255, verbose_name='Mô tả (tùy chọn)')),
                ('achieved_at', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày đạt được')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='tournaments.team', verbose_name='Đội bóng')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_achievements', to='tournaments.tournament', verbose_name='Giải đấu')),
            ],
            options={
                'verbose_name': 'Thành tích Đội bóng',
                'verbose_name_plural': 'Thành tích Đội bóng',
                'ordering': ['-achieved_at'],
                'unique_together': {('team', 'tournament', 'achievement_type')},
            },
        ),
    ]
