# Generated by Django 4.2.13 on 2025-09-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0021_teamachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='main_photo',
            field=models.ImageField(blank=True, help_text='Ảnh toàn đội sẽ hiển thị ở Phòng Truyền thống.', null=True, upload_to='team_main_photos/', verbose_name='Ảnh đại diện đội'),
        ),
    ]
