# Generated by Django 4.2.13 on 2025-09-29 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0022_team_main_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(blank=True, null=True, verbose_name='Phút')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='tournaments.match', verbose_name='Trận đấu')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_in', to='tournaments.player', verbose_name='Cầu thủ vào sân')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_out', to='tournaments.player', verbose_name='Cầu thủ ra sân')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='tournaments.team', verbose_name='Đội')),
            ],
            options={
                'verbose_name': 'Lượt thay người',
                'verbose_name_plural': 'Các lượt thay người',
                'ordering': ['minute'],
            },
        ),
    ]
