# Generated by Django 4.2.13 on 2025-09-29 13:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0023_substitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='substitution',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('MATCH_START', 'Trận đấu bắt đầu'), ('HALF_TIME', 'Hết hiệp 1'), ('MATCH_END', 'Trận đấu kết thúc'), ('EXTRA_TIME_START', 'Hiệp phụ bắt đầu'), ('PENALTY_SHOOTOUT_START', 'Loạt sút luân lưu')], max_length=30, verbose_name='Loại sự kiện')),
                ('text', models.CharField(max_length=255, verbose_name='Nội dung hiển thị')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tournaments.match')),
            ],
            options={
                'verbose_name': 'Sự kiện trận đấu',
                'verbose_name_plural': 'Các sự kiện trận đấu',
                'ordering': ['created_at'],
            },
        ),
    ]
