# Generated by Django 4.2.13 on 2025-09-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0024_add_created_at_to_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournaments.team'),
        ),
    ]
