# Generated by Django 4.2.13 on 2025-09-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0025_alter_lineup_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='transfer_value',
            field=models.PositiveIntegerField(default=0, help_text='Để 0 nếu chưa có định giá.', verbose_name='Giá trị chuyển nhượng (VNĐ)'),
        ),
    ]
