# Generated by Django 4.2.13 on 2025-09-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0026_player_transfer_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Chiều cao (cm)'),
        ),
        migrations.AddField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(blank=True, choices=[('RIGHT', 'Phải'), ('LEFT', 'Trái'), ('BOTH', 'Cả hai')], max_length=5, verbose_name='Chân thuận'),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cân nặng (kg)'),
        ),
    ]
