# Generated by Django 4.2.13 on 2025-09-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0027_player_height_player_preferred_foot_player_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='agent_contact',
            field=models.CharField(blank=True, help_text='Số điện thoại hoặc email của người đại diện.', max_length=200, verbose_name='Thông tin liên hệ (đại diện)'),
        ),
        migrations.AddField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AddField(
            model_name='player',
            name='specialty_position',
            field=models.CharField(blank=True, help_text='Ví dụ: Tiền đạo cắm, Hậu vệ cánh trái...', max_length=100, verbose_name='Vị trí sở trường'),
        ),
        migrations.AddField(
            model_name='player',
            name='votes',
            field=models.PositiveIntegerField(default=0, verbose_name='Số phiếu bình chọn'),
        ),
    ]
