# Generated by Django 4.2.13 on 2025-09-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0028_player_agent_contact_player_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='edit_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Số lần chỉnh sửa'),
        ),
    ]
