# Generated by Django 4.2.13 on 2025-09-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0029_player_edit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MATCH_RESULT', 'Kết quả trận đấu'), ('NEW_TEAM', 'Đội mới đăng ký'), ('DRAW_COMPLETE', 'Bốc thăm hoàn tất'), ('SCHEDULE_CREATED', 'Lịch thi đấu mới'), ('VOTE_AWARDED', 'Nhận phiếu bầu'), ('GENERIC', 'Thông báo chung')], default='GENERIC', max_length=20, verbose_name='Loại thông báo'),
        ),
    ]
