# Generated by Django 4.2.13 on 2025-09-29 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0030_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='Số phiếu')),
                ('voted_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian vote')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament', verbose_name='Giải đấu')),
                ('voted_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='tournaments.player', verbose_name='Cầu thủ được vote')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to=settings.AUTH_USER_MODEL, verbose_name='Người bỏ phiếu')),
            ],
            options={
                'ordering': ['-voted_at'],
                'unique_together': {('voter', 'voted_for', 'tournament')},
            },
        ),
    ]
