# Generated by Django 4.2.13 on 2025-09-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0031_voterecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament'),
        ),
    ]
