# Generated by Django 4.2.13 on 2025-09-30 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_is_profile_complete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0032_alter_team_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role', verbose_name='Vai trò chuyên môn')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='tournaments.tournament', verbose_name='Giải đấu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Thành viên')),
            ],
            options={
                'verbose_name': 'Thành viên chuyên môn',
                'verbose_name_plural': 'Đội ngũ chuyên môn',
                'ordering': ['role'],
                'unique_together': {('tournament', 'user', 'role')},
            },
        ),
    ]
