# Generated by Django 4.2.13 on 2025-10-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0033_tournamentstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='location_detail',
            field=models.CharField(blank=True, help_text='Ví dụ: Hà Nội, Điện Biên, TP.HCM...', max_length=100, verbose_name='Tỉnh/Thành phố'),
        ),
    ]
