# Generated by Django 4.2.13 on 2025-10-01 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0034_tournament_location_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('COMMENTATOR', 'Ghi chú của Bình luận viên'), ('CAPTAIN', 'Ghi chú của Đội trưởng')], max_length=20, verbose_name='Loại ghi chú')),
                ('commentator_notes_team1', models.TextField(blank=True, verbose_name='Ghi chú về Đội 1')),
                ('commentator_notes_team2', models.TextField(blank=True, verbose_name='Ghi chú về Đội 2')),
                ('captain_note', models.TextField(blank=True, verbose_name='Ghi chú gửi BLV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tournaments.match', verbose_name='Trận đấu')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notes', to='tournaments.team', verbose_name='Đội của Đội trưởng')),
            ],
            options={
                'verbose_name': 'Ghi chú Trận đấu',
                'verbose_name_plural': 'Ghi chú Trận đấu',
                'ordering': ['-updated_at'],
                'unique_together': {('match', 'author', 'note_type', 'team')},
            },
        ),
    ]
