# Generated by Django 4.2.13 on 2025-10-06 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0036_alter_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Chưa thanh toán'), ('PENDING', 'Chờ xác nhận'), ('PAID', 'Đã thanh toán')], default='UNPAID', max_length=10, verbose_name='Trạng thái thanh toán')),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Bằng chứng thanh toán')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
            ],
            options={
                'verbose_name': 'Đơn đăng ký của Đội',
                'verbose_name_plural': 'Các đơn đăng ký của Đội',
            },
        ),
        migrations.RemoveConstraint(
            model_name='team',
            name='uniq_team_name_in_tournament',
        ),
        migrations.RemoveField(
            model_name='team',
            name='group',
        ),
        migrations.RemoveField(
            model_name='team',
            name='payment_proof',
        ),
        migrations.RemoveField(
            model_name='team',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tournament',
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='tournaments.group', verbose_name='Bảng đấu'),
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.team', verbose_name='Đội'),
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament', verbose_name='Giải đấu'),
        ),
        migrations.AddField(
            model_name='team',
            name='tournaments',
            field=models.ManyToManyField(blank=True, related_name='teams_registered', through='tournaments.TeamRegistration', to='tournaments.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='teamregistration',
            unique_together={('team', 'tournament')},
        ),
    ]
