# Generated by Django 4.2.13 on 2025-10-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0037_teamregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='transfer_value',
            field=models.PositiveIntegerField(default=0, help_text='Giá trị nền của đội bóng, không bao gồm phiếu bầu.', verbose_name='Giá trị đội bóng (VNĐ)'),
        ),
        migrations.AddField(
            model_name='team',
            name='votes',
            field=models.PositiveIntegerField(default=0, verbose_name='Số phiếu bình chọn'),
        ),
    ]
