# Generated by Django 4.2.13 on 2025-10-06 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0038_team_transfer_value_team_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamVoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='Số phiếu')),
                ('voted_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian vote')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament', verbose_name='Giải đấu')),
                ('voted_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='tournaments.team', verbose_name='Đội được vote')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_votes_cast', to=settings.AUTH_USER_MODEL, verbose_name='Người bỏ phiếu')),
            ],
            options={
                'verbose_name': 'Phiếu bầu cho Đội',
                'verbose_name_plural': 'Các phiếu bầu cho Đội',
                'ordering': ['-voted_at'],
                'unique_together': {('voter', 'voted_for', 'tournament')},
            },
        ),
    ]
