# Generated by Django 4.2.13 on 2025-10-06 16:11

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0039_teamvoterecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='kit_away_color',
            field=colorfield.fields.ColorField(default='#1E293B', image_field=None, max_length=25, samples=None, verbose_name='Màu áo sân khách'),
        ),
        migrations.AddField(
            model_name='team',
            name='kit_home_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Màu áo sân nhà'),
        ),
    ]
