# Generated by Django 4.2.13 on 2025-10-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0040_team_kit_away_color_team_kit_home_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='donation_qr_code',
            field=models.ImageField(blank=True, help_text='Tải lên ảnh mã QR cá nhân (Momo, VNPAY,...) để nhận donate từ người hâm mộ.', null=True, upload_to='player_qrcodes/', verbose_name='Mã QR ủng hộ'),
        ),
    ]
