# Generated by Django 4.2.13 on 2025-10-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0041_player_donation_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ'), ('ACCEPTED', 'Đã chấp nhận'), ('REJECTED', 'Đã từ chối'), ('CANCELED', 'Đã hủy')], default='PENDING', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='tournaments.team', verbose_name='Đội hiện tại')),
                ('inviting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='tournaments.team', verbose_name='Đội mời')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='tournaments.player', verbose_name='Cầu thủ')),
            ],
            options={
                'verbose_name': 'Lời mời Chuyển nhượng',
                'verbose_name_plural': 'Các lời mời Chuyển nhượng',
                'ordering': ['-created_at'],
                'unique_together': {('inviting_team', 'player')},
            },
        ),
    ]
