# Generated by Django 4.2.13 on 2025-10-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0042_playertransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='budget',
            field=models.BigIntegerField(default=50000000, help_text='Ngân sách dùng để thực hiện chuyển nhượng.', verbose_name='Ngân sách (VNĐ)'),
        ),
    ]
