# Generated by Django 4.2.13 on 2025-10-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0043_team_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertransfer',
            name='loan_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn cho mượn'),
        ),
        migrations.AddField(
            model_name='playertransfer',
            name='transfer_type',
            field=models.CharField(choices=[('PERMANENT', 'Mua đứt'), ('LOAN', 'Cho mượn')], default='PERMANENT', max_length=10, verbose_name='Loại hình chuyển nhượng'),
        ),
    ]
