# Generated by Django 4.2.13 on 2025-10-06 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0044_playertransfer_loan_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playertransfer',
            unique_together=set(),
        ),
    ]
