# Generated by Django 4.2.13 on 2025-10-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0045_alter_playertransfer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertransfer',
            name='offer_amount',
            field=models.BigIntegerField(default=0, verbose_name='Số tiền đề nghị (VNĐ)'),
        ),
    ]
