# Generated by Django 4.2.13 on 2025-10-06 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0046_playertransfer_offer_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouted_by', to='tournaments.player', verbose_name='Cầu thủ được theo dõi')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouting_list', to='tournaments.team', verbose_name='Đội bóng theo dõi')),
            ],
            options={
                'verbose_name': 'Danh sách Theo dõi',
                'verbose_name_plural': 'Danh sách Theo dõi',
                'ordering': ['-added_at'],
                'unique_together': {('team', 'player')},
            },
        ),
    ]
