# Generated by Django 4.2.13 on 2025-10-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0047_scoutinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_looking_for_club',
            field=models.BooleanField(default=False, help_text='Đánh dấu nếu cầu thủ này là cầu thủ tự do hoặc muốn tìm một bến đỗ mới.', verbose_name='Đang tìm CLB'),
        ),
        migrations.AddField(
            model_name='player',
            name='region',
            field=models.CharField(choices=[('MIEN_BAC', 'Miền Bắc'), ('MIEN_TRUNG', 'Miền Trung'), ('MIEN_NAM', 'Miền Nam'), ('KHAC', 'Khác')], default='KHAC', help_text='Khu vực hoạt động chính của cầu thủ.', max_length=20, verbose_name='Khu vực'),
        ),
    ]
