# Generated by Django 4.2.13 on 2025-10-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0048_player_is_looking_for_club_player_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='location_detail',
            field=models.CharField(blank=True, help_text='Ví dụ: Hà Nội, Điện Biên, TP.HCM...', max_length=100, verbose_name='Tỉnh / Thành phố'),
        ),
    ]
