# Generated by Django 4.2.13 on 2025-10-07 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0050_player_created_at_player_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(help_text='Ví dụ: Tài trợ Vàng, Đồng hành cùng giải đấu...', max_length=100, verbose_name='Tên gói tài trợ')),
                ('logo', models.ImageField(upload_to='sponsor_logos/', verbose_name='Logo nhà tài trợ')),
                ('website_url', models.URLField(help_text='Link sẽ được gắn vào logo/banner của nhà tài trợ.', verbose_name='Link trang web')),
                ('order', models.PositiveIntegerField(default=0, help_text='Số nhỏ hơn sẽ được hiển thị trước.', verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị công khai')),
                ('sponsor', models.ForeignKey(limit_choices_to={'profile__roles__id': 'SPONSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to=settings.AUTH_USER_MODEL, verbose_name='Nhà tài trợ')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='tournaments.tournament', verbose_name='Giải đấu')),
            ],
            options={
                'verbose_name': 'Nhà tài trợ Giải đấu',
                'verbose_name_plural': 'Các nhà tài trợ Giải đấu',
                'ordering': ['order'],
                'unique_together': {('tournament', 'sponsor')},
            },
        ),
        migrations.CreateModel(
            name='SponsorClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('sponsorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='tournaments.sponsorship')),
            ],
            options={
                'verbose_name': 'Lượt click của Nhà tài trợ',
                'verbose_name_plural': 'Các lượt click của Nhà tài trợ',
                'ordering': ['-timestamp'],
            },
        ),
    ]
