# Generated by Django 4.2.13 on 2025-10-08 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0051_sponsorship_sponsorclick'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sponsorship',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='sponsor_name',
            field=models.CharField(blank=True, help_text='Chỉ điền vào đây nếu nhà tài trợ không có tài khoản trên hệ thống.', max_length=150, verbose_name='Tên Nhà tài trợ (nhập tay)'),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='sponsor',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__roles__id': 'SPONSOR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản Nhà tài trợ (nếu có)'),
        ),
    ]
