# Generated by Django 4.2.13 on 2025-10-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0052_alter_sponsorship_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sponsor_logos/', verbose_name='Logo nhà tài trợ'),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='package_name',
            field=models.CharField(blank=True, help_text='Ví dụ: Tài trợ Vàng, Đồng hành cùng giải đấu...', max_length=100, verbose_name='Tên gói tài trợ'),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='website_url',
            field=models.URLField(blank=True, help_text='Link sẽ được gắn vào logo/banner của nhà tài trợ.', verbose_name='Link trang web'),
        ),
    ]
