# Generated by Django 4.2.13 on 2025-10-08 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0053_alter_sponsorship_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsorship',
            options={'ordering': ['package__order', 'order'], 'verbose_name': 'Nhà tài trợ Giải đấu', 'verbose_name_plural': 'Các nhà tài trợ Giải đấu'},
        ),
        migrations.RemoveField(
            model_name='sponsorship',
            name='package_name',
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sponsor_logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Số nhỏ hơn hiển thị trước.', verbose_name='Thứ tự trong gói'),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='sponsor_name',
            field=models.CharField(blank=True, help_text='Chỉ điền nếu NTT không có tài khoản trên hệ thống.', max_length=150, verbose_name='Tên Nhà tài trợ (nhập tay)'),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='Link trang web'),
        ),
        migrations.CreateModel(
            name='SponsorshipPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên gói')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Mức tài trợ (VNĐ)')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả quyền lợi')),
                ('order', models.PositiveIntegerField(default=0, help_text='Số nhỏ hơn sẽ hiển thị trước (Vàng: 0, Bạc: 1, ...).', verbose_name='Thứ tự ưu tiên')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_packages', to='tournaments.tournament', verbose_name='Giải đấu')),
            ],
            options={
                'verbose_name': 'Gói tài trợ',
                'verbose_name_plural': 'Các gói tài trợ',
                'ordering': ['order', '-price'],
            },
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.sponsorshippackage', verbose_name='Gói tài trợ'),
        ),
    ]
