# Generated by Django 4.2.13 on 2025-10-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0054_alter_sponsorship_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='status',
            field=models.CharField(choices=[('POTENTIAL', 'Tiềm năng'), ('CONTACTED', 'Đã liên hệ'), ('CONFIRMED', 'Đã chốt'), ('PAID', 'Đã thanh toán'), ('COMPLETED', 'Hoàn thành')], db_index=True, default='POTENTIAL', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
