# Generated by Django 4.2.13 on 2025-10-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0055_sponsorship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='benefits_checklist',
            field=models.JSONField(blank=True, default=list, verbose_name='Checklist Quyền lợi'),
        ),
        migrations.AddField(
            model_name='sponsorshippackage',
            name='benefits',
            field=models.TextField(blank=True, help_text='Nhập mỗi quyền lợi trên một dòng. Ví dụ: Treo banner tại sân, Nhắc tên trên livestream...', verbose_name='Danh sách quyền lợi'),
        ),
    ]
