# Generated by Django 4.2.13 on 2025-10-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0056_sponsorship_benefits_checklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorshippackage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Mức tài trợ (VNĐ)'),
        ),
    ]
