# Generated by Django 4.2.13 on 2025-10-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0057_alter_sponsorshippackage_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('CUP', 'Đá Cúp (loại trực tiếp/vòng bảng + knock-out)'), ('LEAGUE', 'Đá League (vòng tròn tính điểm)')], default='CUP', help_text='Chọn thể thức thi đấu của giải', max_length=10, verbose_name='Thể thức'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_round',
            field=models.CharField(choices=[('LEAGUE', 'League'), ('GROUP', 'Vòng bảng'), ('QUARTER', 'Tứ kết'), ('SEMI', 'Bán kết'), ('THIRD_PLACE', 'Tranh Hạng Ba'), ('FINAL', 'Chung kết')], default='GROUP', max_length=20),
        ),
    ]
