# Generated by Django 4.2.13 on 2025-10-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0058_tournament_format_alter_match_match_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='leg',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1 = lượt đi, 2 = lượt về', null=True, verbose_name='Lượt'),
        ),
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Vòng'),
        ),
    ]
