# Generated by Django 4.2.13 on 2025-10-10 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0059_match_leg_match_round_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_budget', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Ngân sách ban đầu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Ngân sách giải đấu',
                'verbose_name_plural': 'Ngân sách giải đấu',
            },
        ),
        migrations.CreateModel(
            name='RevenueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TEAM_FEES', 'Phí đăng ký đội'), ('SPONSORSHIP', 'Tài trợ'), ('PENALTIES', 'Tiền phạt'), ('TICKETS', 'Bán vé'), ('MERCHANDISE', 'Bán hàng hóa'), ('OTHER', 'Khác')], max_length=20, verbose_name='Danh mục')),
                ('description', models.CharField(max_length=200, verbose_name='Mô tả')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Số tiền')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('is_auto_calculated', models.BooleanField(default=False, verbose_name='Tự động tính')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_items', to='tournaments.tournamentbudget')),
            ],
            options={
                'verbose_name': 'Khoản thu',
                'verbose_name_plural': 'Khoản thu',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('VENUE', 'Tiền sân bãi'), ('REFEREE', 'Trọng tài'), ('LIVESTREAM', 'Livestream'), ('PHOTOGRAPHY', 'Chụp ảnh'), ('TROPHIES', 'Cờ cúp, huy chương'), ('REFRESHMENTS', 'Nước uống'), ('TRANSPORTATION', 'Đi lại'), ('EQUIPMENT', 'Thiết bị'), ('MARKETING', 'Marketing'), ('OTHER', 'Khác')], max_length=20, verbose_name='Danh mục')),
                ('description', models.CharField(max_length=200, verbose_name='Mô tả')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Số tiền')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expense_receipts/', verbose_name='Hóa đơn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='tournaments.tournamentbudget')),
            ],
            options={
                'verbose_name': 'Khoản chi',
                'verbose_name_plural': 'Khoản chi',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Hành động')),
                ('description', models.CharField(max_length=200, verbose_name='Mô tả')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Số tiền')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tournaments.tournamentbudget')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Lịch sử ngân sách',
                'verbose_name_plural': 'Lịch sử ngân sách',
                'ordering': ['-timestamp'],
            },
        ),
    ]
