# Generated by Django 4.2.13 on 2025-10-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0060_tournamentbudget_revenueitem_expenseitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registration_fee',
            field=models.DecimalField(decimal_places=0, default=500000, help_text='Phí đăng ký cho mỗi đội tham gia', max_digits=15, verbose_name='Phí đăng ký (VNĐ)'),
        ),
    ]
