# Generated by Django 4.2.13 on 2025-10-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0061_tournament_registration_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachRecruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ'), ('ACCEPTED', 'Đã chấp nhận'), ('REJECTED', 'Đã từ chối'), ('CANCELED', 'Đã hủy')], default='PENDING', max_length=10, verbose_name='Trạng thái')),
                ('salary_offer', models.DecimalField(blank=True, decimal_places=0, help_text='Mức lương/thù lao cho HLV', max_digits=15, null=True, verbose_name='Mức lương đề nghị (VNĐ)')),
                ('contract_duration', models.CharField(blank=True, help_text='Ví dụ: 1 năm, 6 tháng...', max_length=100, verbose_name='Thời hạn hợp đồng')),
                ('message', models.TextField(blank=True, help_text='Lời mời từ đội trưởng/ban quản lý', verbose_name='Lời nhắn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chiêu mộ Huấn luyện viên',
                'verbose_name_plural': 'Chiêu mộ Huấn luyện viên',
                'ordering': ['-created_at'],
            },
        ),
    ]
