# Generated by Django 4.2.13 on 2025-10-13 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0062_coachrecruitment'),
        ('users', '0019_alter_role_id_stadiumprofile_coachprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_coaching', to='users.coachprofile', verbose_name='Huấn luyện viên'),
        ),
        migrations.AlterField(
            model_name='team',
            name='coach_name',
            field=models.CharField(blank=True, help_text="Tên HLV (sử dụng cho dữ liệu cũ, nên dùng trường 'coach' bên dưới)", max_length=100),
        ),
        migrations.AddField(
            model_name='coachrecruitment',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_offers', to='users.coachprofile', verbose_name='Huấn luyện viên'),
        ),
        migrations.AddField(
            model_name='coachrecruitment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_recruitments', to='tournaments.team', verbose_name='Đội bóng'),
        ),
    ]
