# Generated by Django 4.2.13 on 2025-10-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0063_team_coach_alter_team_coach_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='shop_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Phần trăm giảm giá từ shop áp dụng vào phí đăng ký (0-100%)', max_digits=5, verbose_name='Phần trăm giảm giá từ shop (%)'),
        ),
    ]
