# Generated by Django 4.2.13 on 2025-10-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0065_alter_tournament_shop_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamregistration',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Chưa thanh toán'), ('PENDING', 'Chờ xác nhận'), ('PAID', 'Đã thanh toán'), ('REJECTED', 'Từ chối')], default='UNPAID', max_length=10, verbose_name='Trạng thái thanh toán'),
        ),
    ]
