# Generated by Django 4.2.13 on 2025-10-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0066_alter_teamregistration_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MATCH_RESULT', 'Kết quả trận đấu'), ('NEW_TEAM', 'Đội mới đăng ký'), ('DRAW_COMPLETE', 'Bốc thăm hoàn tất'), ('SCHEDULE_CREATED', 'Lịch thi đấu mới'), ('VOTE_AWARDED', 'Nhận phiếu bầu'), ('player_claim_request', 'Yêu cầu liên kết cầu thủ'), ('player_claim_confirmed', 'Liên kết cầu thủ thành công'), ('player_claim_rejected', 'Yêu cầu liên kết bị từ chối'), ('GENERIC', 'Thông báo chung')], default='GENERIC', max_length=30, verbose_name='Loại thông báo'),
        ),
    ]
