# Generated by Django 4.2.13 on 2025-10-15 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0068_notification_related_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTeamExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_type', models.CharField(choices=[('IMMEDIATE', 'Rời ngay lập tức'), ('END_SEASON', 'Rời cuối mùa giải')], default='IMMEDIATE', max_length=15, verbose_name='Loại rời đội')),
                ('reason', models.TextField(blank=True, help_text='Giải thích lý do muốn rời đội (không bắt buộc)', verbose_name='Lý do rời đội')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=10, verbose_name='Trạng thái')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Ghi chú từ đội trưởng về việc xử lý yêu cầu', verbose_name='Ghi chú của đội trưởng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_requests_received', to='tournaments.team', verbose_name='Đội hiện tại')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_requests', to='tournaments.player', verbose_name='Cầu thủ')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_exit_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
            ],
            options={
                'verbose_name': 'Yêu cầu Rời đội',
                'verbose_name_plural': 'Yêu cầu Rời đội',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='playerteamexit',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('player', 'status'), name='unique_pending_exit_request_per_player'),
        ),
    ]
