# Generated by Django 4.2.13 on 2025-10-15 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0069_add_player_team_exit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertransfer',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='tournaments.team', verbose_name='Đội hiện tại'),
        ),
    ]
