# Generated by Django 4.2.13 on 2025-10-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0071_add_player_recruitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Ảnh bìa hiển thị trên trang hồ sơ cầu thủ. Khuyến nghị: 1920x400px.', null=True, upload_to='player_banners/', verbose_name='Ảnh bìa hồ sơ'),
        ),
        migrations.DeleteModel(
            name='PlayerRecruitment',
        ),
    ]
