# Generated by Django 4.2.13 on 2025-10-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0072_add_player_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='banner_image',
        ),
        migrations.AddField(
            model_name='team',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Ảnh bìa hiển thị ở đầu trang hồ sơ (khuyến nghị: 1920x400px)', null=True, upload_to='team_banners/', verbose_name='Ảnh bìa hồ sơ'),
        ),
    ]
