# Generated by Django 4.2.13 on 2025-10-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0073_add_banner_image_to_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Ảnh bìa hiển thị ở đầu trang hồ sơ (khuyến nghị: 1920x400px)', null=True, upload_to='player_banners/', verbose_name='Ảnh bìa hồ sơ'),
        ),
    ]
