# Generated by Django 4.2.13 on 2025-10-16 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0025_add_banner_image_to_stadium_profile'),
        ('tournaments', '0074_player_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_unit', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Giá tiền/đơn vị')),
                ('payment_unit', models.CharField(choices=[('PER_MATCH', 'Theo trận'), ('PER_DAY', 'Theo ngày'), ('PER_TOURNAMENT', 'Theo giải đấu'), ('HOURLY', 'Theo giờ')], default='PER_MATCH', max_length=20, verbose_name='Đơn vị tính')),
                ('number_of_units', models.PositiveIntegerField(default=1, verbose_name='Số đơn vị')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Tổng tiền công')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role', verbose_name='Vai trò')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tournaments.tournamentstaff', verbose_name='Thành viên')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_payments', to='tournaments.tournament', verbose_name='Giải đấu')),
            ],
            options={
                'verbose_name': 'Tiền công nhân viên',
                'verbose_name_plural': 'Tiền công nhân viên',
                'ordering': ['-created_at'],
                'unique_together': {('tournament', 'staff_member', 'role')},
            },
        ),
    ]
