# Generated by Django 4.2.13 on 2025-10-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0075_add_staff_payment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='shop_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Phần trăm tiền lãi từ shop được trừ vào phí đăng ký (0-100%)', max_digits=5, verbose_name='Phần trăm tiền lãi từ shop (%)'),
        ),
    ]
