# Generated by Django 4.2.13 on 2025-10-11 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Danh mục blog',
                'verbose_name_plural': 'Danh mục blog',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên tag')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Màu tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(max_length=500, verbose_name='Tóm tắt')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='Ảnh đại diện')),
                ('post_type', models.CharField(choices=[('news', 'Tin tức'), ('review', 'Review sản phẩm'), ('guide', 'Hướng dẫn'), ('tips', 'Mẹo hay')], default='news', max_length=20, verbose_name='Loại bài viết')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã xuất bản'), ('archived', 'Lưu trữ')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='Meta description')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Bài viết nổi bật')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='Lượt thích')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xuất bản')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategory', verbose_name='Danh mục')),
                ('tags', models.ManyToManyField(blank=True, to='blog.blogtag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Bài viết blog',
                'verbose_name_plural': 'Bài viết blog',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Tên tác giả')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email tác giả')),
                ('content', models.TextField(verbose_name='Nội dung bình luận')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Đã duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost', verbose_name='Bài viết')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận',
                'ordering': ['-created_at'],
            },
        ),
    ]
