# Generated by Django 4.2.13 on 2025-09-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_notify_draw_results_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(choices=[('ORGANIZER', 'Ban Tổ chức'), ('PLAYER', 'Cầu thủ'), ('COMMENTATOR', 'Bình Luận Viên'), ('MEDIA', 'Đơn Vị Truyền Thông'), ('PHOTOGRAPHER', 'Nhiếp Ảnh Gia'), ('COLLABORATOR', 'Cộng Tác Viên')], max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Tên vai trò')),
                ('icon', models.CharField(help_text='Ví dụ: bi-shield-check', max_length=50, verbose_name='Tên icon (Bootstrap Icons)')),
                ('description', models.TextField(verbose_name='Mô tả vai trò')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='has_selected_roles',
            field=models.BooleanField(default=False, verbose_name='Đã chọn vai trò lần đầu'),
        ),
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='users.role', verbose_name='Các vai trò đã chọn'),
        ),
    ]
