# Generated by Django 4.2.13 on 2025-09-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Một vài dòng về kỹ năng, đam mê hoặc thành tích của bạn.', verbose_name='Giới thiệu bản thân'),
        ),
        migrations.AddField(
            model_name='profile',
            name='equipment',
            field=models.CharField(blank=True, help_text='Liệt kê các thiết bị chuyên dụng nếu có (máy ảnh, flycam, micro...).', max_length=255, verbose_name='Thiết bị sở hữu'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.PositiveIntegerField(blank=True, help_text='Để trống nếu không áp dụng.', null=True, verbose_name='Số năm kinh nghiệm'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='Ví dụ: Hà Nội, TP.HCM, Điện Biên...', max_length=100, verbose_name='Khu vực hoạt động'),
        ),
    ]
