# Generated by Django 4.2.13 on 2025-09-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_bio_profile_equipment_profile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_profile_complete',
            field=models.BooleanField(default=False, verbose_name='Đã hoàn tất hồ sơ lần đầu'),
        ),
    ]
