# Generated by Django 4.2.13 on 2025-09-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_manager_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(choices=[('ORGANIZER', 'Ban Tổ chức'), ('PLAYER', 'Cầu thủ'), ('COMMENTATOR', 'Bình Luận Viên'), ('MEDIA', 'Đơn Vị Truyền Thông'), ('PHOTOGRAPHER', 'Nhiếp Ảnh Gia'), ('COLLABORATOR', 'Cộng Tác Viên'), ('TOURNAMENT_MANAGER', 'Quản lý Giải đấu')], max_length=20, primary_key=True, serialize=False),
        ),
    ]
