# Generated by Django 4.2.13 on 2025-10-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_role_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='role',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Số nhỏ hơn sẽ được hiển thị trước.', verbose_name='Thứ tự hiển thị'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(choices=[('ORGANIZER', 'Ban Tổ chức'), ('PLAYER', 'Cầu thủ'), ('COMMENTATOR', 'Bình Luận Viên'), ('MEDIA', 'Đơn Vị Truyền Thông'), ('REFEREE', 'Trọng tài'), ('PHOTOGRAPHER', 'Nhiếp Ảnh Gia'), ('TOURNAMENT_MANAGER', 'Quản lý Giải đấu'), ('COLLABORATOR', 'Cộng Tác Viên')], max_length=20, primary_key=True, serialize=False),
        ),
    ]
