# Generated by Django 4.2.13 on 2025-10-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='brand_website',
            field=models.URLField(blank=True, max_length=255, verbose_name='Website Thương hiệu'),
        ),
        migrations.AddField(
            model_name='profile',
            name='referee_level',
            field=models.CharField(blank=True, help_text='Ví dụ: Chứng chỉ Futsal, Trọng tài Quận, v.v.', max_length=100, verbose_name='Cấp độ Trọng tài'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sponsorship_interests',
            field=models.CharField(blank=True, help_text='Ví dụ: Giải đấu U21, Đội bóng doanh nghiệp, Cầu thủ trẻ...', max_length=255, verbose_name='Lĩnh vực quan tâm tài trợ'),
        ),
    ]
