# Generated by Django 4.2.13 on 2025-10-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_brand_website_profile_referee_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role_change_count',
            field=models.IntegerField(default=0),
        ),
    ]
