# Generated by Django 4.2.13 on 2025-10-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_role_change_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role_change_count',
            field=models.PositiveIntegerField(default=0, help_text='Số lần người dùng đã thay đổi vai trò.'),
        ),
    ]
