# Generated by Django 4.2.13 on 2025-10-13 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0062_coachrecruitment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0018_alter_profile_role_change_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(choices=[('ORGANIZER', 'Ban Tổ chức'), ('PLAYER', 'Cầu thủ'), ('COMMENTATOR', 'Bình Luận Viên'), ('MEDIA', 'Đơn Vị Truyền Thông'), ('PHOTOGRAPHER', 'Nhiếp Ảnh Gia'), ('COLLABORATOR', 'Cộng Tác Viên'), ('TOURNAMENT_MANAGER', 'Quản lý Giải đấu'), ('REFEREE', 'Trọng tài'), ('SPONSOR', 'Nhà tài trợ'), ('COACH', 'Huấn luyện viên'), ('STADIUM', 'Sân bóng')], max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='StadiumProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadium_name', models.CharField(max_length=150, verbose_name='Tên sân')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stadium_logos/', verbose_name='Logo/Ảnh sân')),
                ('description', models.TextField(blank=True, help_text='Giới thiệu về sân bóng, cơ sở vật chất...', verbose_name='Mô tả')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ chi tiết')),
                ('region', models.CharField(choices=[('MIEN_BAC', 'Miền Bắc'), ('MIEN_TRUNG', 'Miền Trung'), ('MIEN_NAM', 'Miền Nam'), ('KHAC', 'Khác')], default='KHAC', max_length=20, verbose_name='Khu vực')),
                ('location_detail', models.CharField(blank=True, max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email liên hệ')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('field_type', models.CharField(choices=[('GRASS_11', 'Sân cỏ tự nhiên 11 người'), ('GRASS_7', 'Sân cỏ tự nhiên 7 người'), ('GRASS_5', 'Sân cỏ tự nhiên 5 người'), ('ARTIFICIAL_11', 'Sân cỏ nhân tạo 11 người'), ('ARTIFICIAL_7', 'Sân cỏ nhân tạo 7 người'), ('ARTIFICIAL_5', 'Sân cỏ nhân tạo 5 người'), ('FUTSAL', 'Sân Futsal'), ('OTHER', 'Khác')], default='ARTIFICIAL_7', max_length=50, verbose_name='Loại sân')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sức chứa khán giả')),
                ('number_of_fields', models.PositiveIntegerField(default=1, verbose_name='Số sân')),
                ('amenities', models.TextField(blank=True, help_text='Ví dụ: Phòng thay đồ, Bãi đỗ xe, Căn tin, Hệ thống đèn, Camera...', verbose_name='Tiện ích')),
                ('rental_price_range', models.CharField(blank=True, help_text='Ví dụ: 500.000 - 1.000.000 VNĐ/giờ', max_length=100, verbose_name='Giá thuê (khoảng)')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Tên ngân hàng')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='Số tài khoản')),
                ('bank_account_name', models.CharField(blank=True, max_length=100, verbose_name='Tên chủ tài khoản')),
                ('payment_qr_code', models.ImageField(blank=True, null=True, upload_to='stadium_qr_codes/', verbose_name='Mã QR thanh toán')),
                ('operating_hours', models.TextField(blank=True, help_text='Ví dụ: Thứ 2-7: 6h-22h, Chủ nhật: 6h-20h', verbose_name='Giờ hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stadium_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Hồ sơ Sân bóng',
                'verbose_name_plural': 'Hồ sơ Sân bóng',
            },
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='coach_avatars/', verbose_name='Ảnh đại diện')),
                ('bio', models.TextField(blank=True, help_text='Kinh nghiệm, triết lý huấn luyện...', verbose_name='Giới thiệu bản thân')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số năm kinh nghiệm')),
                ('coaching_license', models.CharField(blank=True, help_text='Ví dụ: AFC C, UEFA B...', max_length=200, verbose_name='Chứng chỉ HLV')),
                ('specialization', models.CharField(blank=True, help_text='Ví dụ: Huấn luyện thể lực, Chiến thuật...', max_length=200, verbose_name='Chuyên môn')),
                ('achievements', models.TextField(blank=True, help_text='Các danh hiệu, giải thưởng đã đạt được', verbose_name='Thành tích nổi bật')),
                ('previous_teams', models.TextField(blank=True, help_text='Lịch sử công tác', verbose_name='Đội đã từng huấn luyện')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email liên hệ')),
                ('region', models.CharField(choices=[('MIEN_BAC', 'Miền Bắc'), ('MIEN_TRUNG', 'Miền Trung'), ('MIEN_NAM', 'Miền Nam'), ('KHAC', 'Khác')], default='KHAC', max_length=20, verbose_name='Khu vực')),
                ('location_detail', models.CharField(blank=True, max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('is_available', models.BooleanField(default=False, help_text='Đánh dấu nếu đang tìm đội bóng để huấn luyện', verbose_name='Đang tìm đội')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='tournaments.team', verbose_name='Đội đang huấn luyện')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Hồ sơ Huấn luyện viên',
                'verbose_name_plural': 'Hồ sơ Huấn luyện viên',
            },
        ),
    ]
