# Generated by Django 4.2.13 on 2025-10-13 22:06

from django.db import migrations


def create_new_roles(apps, schema_editor):
    """Thêm 2 vai trò mới: COACH và STADIUM"""
    Role = apps.get_model('users', 'Role')
    
    # Tạo vai trò Huấn luyện viên
    Role.objects.get_or_create(
        id='COACH',
        defaults={
            'name': 'Huấn luyện viên',
            'icon': 'bi-clipboard-check',
            'description': 'Huấn luyện viên của đội bóng, có quyền quản lý đội như đội trưởng',
            'order': 10
        }
    )
    
    # Tạo vai trò Sân bóng
    Role.objects.get_or_create(
        id='STADIUM',
        defaults={
            'name': 'Sân bóng',
            'icon': 'bi-house',
            'description': 'Chủ sân bóng, có thể đăng tin tuyển dụng và được thêm vào nhân sự/nhà tài trợ',
            'order': 11
        }
    )


def remove_new_roles(apps, schema_editor):
    """Xóa 2 vai trò mới nếu rollback"""
    Role = apps.get_model('users', 'Role')
    Role.objects.filter(id__in=['COACH', 'STADIUM']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_role_id_stadiumprofile_coachprofile'),
    ]

    operations = [
        migrations.RunPython(create_new_roles, remove_new_roles),
    ]
