# Generated by Django 4.2.13 on 2025-10-14 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0063_team_coach_alter_team_coach_name_and_more'),
        ('users', '0020_add_coach_stadium_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='StadiumReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], default=5, verbose_name='Xếp hạng (sao)')),
                ('comment', models.TextField(blank=True, help_text='Chia sẻ cảm nhận về chất lượng sân bóng', max_length=1000, verbose_name='Nội dung nhận xét')),
                ('is_approved', models.BooleanField(default=True, help_text='Sân bóng có thể chọn ẩn/hiện nhận xét này', verbose_name='Được hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_stadium_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
                ('stadium_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.stadiumprofile', verbose_name='Sân bóng')),
                ('team', models.ForeignKey(blank=True, help_text='Đội bóng đã sử dụng sân', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.team', verbose_name='Đội bóng')),
                ('tournament', models.ForeignKey(blank=True, help_text='Giải đấu tổ chức tại sân', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament', verbose_name='Giải đấu')),
            ],
            options={
                'verbose_name': 'Đánh giá Sân bóng',
                'verbose_name_plural': 'Các Đánh giá Sân bóng',
                'ordering': ['-created_at'],
                'unique_together': {('stadium_profile', 'reviewer', 'team')},
            },
        ),
        migrations.CreateModel(
            name='CoachReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], default=5, verbose_name='Xếp hạng (sao)')),
                ('comment', models.TextField(blank=True, help_text='Chia sẻ cảm nhận về chất lượng huấn luyện', max_length=1000, verbose_name='Nội dung nhận xét')),
                ('is_approved', models.BooleanField(default=True, help_text='HLV có thể chọn ẩn/hiện nhận xét này', verbose_name='Được hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.coachprofile', verbose_name='Huấn luyện viên')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_coach_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
                ('team', models.ForeignKey(blank=True, help_text='Đội bóng mà HLV đã huấn luyện', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.team', verbose_name='Đội bóng')),
                ('tournament', models.ForeignKey(blank=True, help_text='Giải đấu liên quan', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament', verbose_name='Giải đấu')),
            ],
            options={
                'verbose_name': 'Đánh giá HLV',
                'verbose_name_plural': 'Các Đánh giá HLV',
                'ordering': ['-created_at'],
                'unique_together': {('coach_profile', 'reviewer', 'team')},
            },
        ),
    ]
