# Generated by Django 4.2.13 on 2025-10-14 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0022_add_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, verbose_name='Tên thương hiệu')),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='sponsor_logos/', verbose_name='Logo thương hiệu')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='Slogan/Khẩu hiệu')),
                ('description', models.TextField(blank=True, help_text='Mô tả về thương hiệu, sản phẩm, dịch vụ...', verbose_name='Giới thiệu chi tiết')),
                ('website_url', models.URLField(blank=True, verbose_name='Website')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email liên hệ')),
                ('sponsorship_interests', models.CharField(blank=True, help_text='Ví dụ: Giải đấu U21, Đội bóng doanh nghiệp, Cầu thủ trẻ...', max_length=255, verbose_name='Lĩnh vực quan tâm tài trợ')),
                ('budget_range', models.CharField(blank=True, help_text='Ví dụ: 10-50 triệu VNĐ, 100-500 triệu VNĐ...', max_length=100, verbose_name='Khoảng ngân sách tài trợ')),
                ('payment_qr_code', models.ImageField(blank=True, help_text='Mã QR để nhận thanh toán/donate', null=True, upload_to='sponsor_qr_codes/', verbose_name='Mã QR thanh toán')),
                ('region', models.CharField(choices=[('MIEN_BAC', 'Miền Bắc'), ('MIEN_TRUNG', 'Miền Trung'), ('MIEN_NAM', 'Miền Nam'), ('KHAC', 'Khác')], default='KHAC', max_length=20, verbose_name='Khu vực')),
                ('location_detail', models.CharField(blank=True, max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('is_active', models.BooleanField(default=True, help_text='Đánh dấu nếu đang tìm cơ hội tài trợ', verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_sponsor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Hồ sơ Nhà tài trợ',
                'verbose_name_plural': 'Hồ sơ Nhà tài trợ',
            },
        ),
    ]
