# Generated by Django 4.2.13 on 2025-10-14 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0023_sponsorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản'),
        ),
    ]
