# Generated by Django 4.2.13 on 2025-10-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_sponsorprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadiumprofile',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Ảnh bìa hiển thị ở đầu trang hồ sơ (khuyến nghị: 1920x400px)', null=True, upload_to='stadium_banners/', verbose_name='Ảnh bìa hồ sơ'),
        ),
    ]
