# Generated by Django 4.2.13 on 2025-10-18 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Playlist')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('folder_path', models.CharField(max_length=200, verbose_name='Đường dẫn thư mục')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MusicPlayerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_play', models.BooleanField(default=True, verbose_name='Tự động phát')),
                ('volume', models.FloatField(default=0.7, verbose_name='Âm lượng')),
                ('repeat_mode', models.CharField(choices=[('none', 'Không lặp'), ('one', 'Lặp một bài'), ('all', 'Lặp tất cả')], default='all', max_length=20, verbose_name='Chế độ lặp')),
                ('shuffle', models.BooleanField(default=False, verbose_name='Phát ngẫu nhiên')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music_player.playlist', verbose_name='Playlist mặc định')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cài đặt Music Player',
                'verbose_name_plural': 'Cài đặt Music Player',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên bài hát')),
                ('artist', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nghệ sĩ')),
                ('file_path', models.CharField(max_length=500, verbose_name='Đường dẫn file')),
                ('duration', models.IntegerField(default=0, verbose_name='Thời lượng (giây)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music_player.playlist')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
                'ordering': ['playlist', 'order', 'title'],
                'unique_together': {('playlist', 'file_path')},
            },
        ),
    ]
