# Generated by Django 4.2.13 on 2025-10-19 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Playlist')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_public', models.BooleanField(default=False, verbose_name='Công khai')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Playlist Cá Nhân',
                'verbose_name_plural': 'Playlists Cá Nhân',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='musicplayersettings',
            name='upload_quota',
            field=models.IntegerField(default=69, verbose_name='Giới hạn số bài upload'),
        ),
        migrations.CreateModel(
            name='UserTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên bài hát')),
                ('artist', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nghệ sĩ')),
                ('album', models.CharField(blank=True, max_length=200, null=True, verbose_name='Album')),
                ('file', models.FileField(upload_to='music/user_uploads/%Y/%m/', verbose_name='File nhạc')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Kích thước file (bytes)')),
                ('duration', models.IntegerField(default=0, verbose_name='Thời lượng (giây)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bài Hát Cá Nhân',
                'verbose_name_plural': 'Bài Hát Cá Nhân',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music_player.userplaylist')),
                ('user_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='music_player.usertrack')),
            ],
            options={
                'verbose_name': 'Track trong Playlist',
                'verbose_name_plural': 'Tracks trong Playlist',
                'ordering': ['playlist', 'order'],
                'unique_together': {('playlist', 'user_track')},
            },
        ),
    ]
