# Generated by Django 4.2.13 on 2025-10-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0002_userplaylist_musicplayersettings_upload_quota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicplayersettings',
            name='storage_quota_mb',
            field=models.IntegerField(default=500, verbose_name='Giới hạn dung lượng (MB)'),
        ),
        migrations.AlterField(
            model_name='musicplayersettings',
            name='upload_quota',
            field=models.IntegerField(default=69, verbose_name='Giới hạn số bài upload (deprecated)'),
        ),
    ]
