# Generated by Django 4.2.13 on 2025-10-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0003_musicplayersettings_storage_quota_mb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicplayersettings',
            name='storage_quota_mb',
            field=models.IntegerField(default=369, verbose_name='Giới hạn dung lượng (MB)'),
        ),
    ]
