# Generated by Django 4.2.13 on 2025-10-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0004_alter_musicplayersettings_storage_quota_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrack',
            name='album_cover',
            field=models.ImageField(blank=True, null=True, upload_to='music/album_covers/%Y/%m/', verbose_name='Ảnh bìa Album'),
        ),
    ]
