# Generated by Django 4.2.13 on 2025-10-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0005_usertrack_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplaylist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='music/playlist_covers/%Y/%m/', verbose_name='Ảnh Bìa Playlist'),
        ),
    ]
