# Generated by Django 4.2.13 on 2025-10-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0006_userplaylist_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='music/playlist_covers/', verbose_name='Ảnh Bìa Playlist'),
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Album'),
        ),
        migrations.AddField(
            model_name='track',
            name='album_cover',
            field=models.ImageField(blank=True, null=True, upload_to='music/album_covers/', verbose_name='Ảnh Bìa Album'),
        ),
    ]
