# Generated by Django 4.2.13 on 2025-10-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0007_playlist_cover_image_track_album_track_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicplayersettings',
            name='listening_lock',
            field=models.BooleanField(default=False, verbose_name='Khóa chế độ nghe nhạc'),
        ),
    ]
