# Generated by Django 4.2.13 on 2025-10-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0008_musicplayersettings_listening_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicplayersettings',
            name='low_power_mode',
            field=models.BooleanField(default=False, verbose_name='Chế độ máy yếu'),
        ),
    ]
