# Generated by Django 4.2.13 on 2025-10-20 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_player', '0009_musicplayersettings_low_power_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='play_count',
            field=models.IntegerField(default=0, verbose_name='Lượt nghe'),
        ),
        migrations.AddField(
            model_name='usertrack',
            name='play_count',
            field=models.IntegerField(default=0, verbose_name='Lượt nghe'),
        ),
        migrations.CreateModel(
            name='TrackPlayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời gian nghe')),
                ('listen_duration', models.IntegerField(default=0, verbose_name='Thời lượng nghe (giây)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Nghe hết bài')),
                ('track_title', models.CharField(max_length=200, verbose_name='Tên bài hát')),
                ('track_artist', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nghệ sĩ')),
                ('track_duration', models.IntegerField(default=0, verbose_name='Thời lượng track (giây)')),
                ('global_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='play_history', to='music_player.track', verbose_name='Track Global')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('user_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='play_history', to='music_player.usertrack', verbose_name='Track Cá Nhân')),
            ],
            options={
                'verbose_name': 'Lịch Sử Nghe',
                'verbose_name_plural': 'Lịch Sử Nghe',
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['user', '-played_at'], name='music_playe_user_id_c98456_idx'), models.Index(fields=['global_track', '-played_at'], name='music_playe_global__9cd2cc_idx'), models.Index(fields=['user_track', '-played_at'], name='music_playe_user_tr_0b67b4_idx')],
            },
        ),
    ]
