# Generated by Django 4.2.13 on 2025-10-23 23:15

from django.db import migrations, models
import music_player.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0010_track_play_count_usertrack_play_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrack',
            name='file',
            field=models.FileField(upload_to=music_player.models.sanitize_filename, verbose_name='File nhạc'),
        ),
    ]
