# Generated by Django 4.2.13 on 2025-10-24 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_player', '0011_alter_usertrack_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_title', models.CharField(max_length=200, verbose_name='Tên bài hát')),
                ('track_artist', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nghệ sĩ')),
                ('track_album', models.CharField(blank=True, max_length=200, null=True, verbose_name='Album')),
                ('track_duration', models.IntegerField(default=0, verbose_name='Thời lượng (giây)')),
                ('track_type', models.CharField(choices=[('global', 'Global'), ('user', 'User')], max_length=20, verbose_name='Loại Track')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian lưu')),
                ('global_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='music_player.track', verbose_name='Track Global')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_tracks', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('user_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='music_player.usertrack', verbose_name='Track Cá Nhân')),
            ],
            options={
                'verbose_name': 'Bài Hát Đã Lưu',
                'verbose_name_plural': 'Bài Hát Đã Lưu',
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user', '-saved_at'], name='music_playe_user_id_41e884_idx'), models.Index(fields=['global_track'], name='music_playe_global__ef8678_idx'), models.Index(fields=['user_track'], name='music_playe_user_tr_39c30e_idx')],
                'unique_together': {('user', 'user_track'), ('user', 'global_track')},
            },
        ),
        migrations.CreateModel(
            name='SavedPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=200, verbose_name='Tên Playlist')),
                ('playlist_description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('playlist_type', models.CharField(choices=[('global', 'Global'), ('user', 'User')], max_length=20, verbose_name='Loại Playlist')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian lưu')),
                ('global_playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='music_player.playlist', verbose_name='Playlist Global')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_playlists', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('user_playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='music_player.userplaylist', verbose_name='Playlist Cá Nhân')),
            ],
            options={
                'verbose_name': 'Playlist Đã Lưu',
                'verbose_name_plural': 'Playlist Đã Lưu',
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user', '-saved_at'], name='music_playe_user_id_661c3b_idx'), models.Index(fields=['global_playlist'], name='music_playe_global__e8b2a7_idx'), models.Index(fields=['user_playlist'], name='music_playe_user_pl_28506c_idx')],
                'unique_together': {('user', 'global_playlist'), ('user', 'user_playlist')},
            },
        ),
    ]
