# Generated by Django 4.2.13 on 2025-10-25 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_player', '0012_savedtrack_savedplaylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicplayersettings',
            name='upload_quota',
        ),
        migrations.CreateModel(
            name='UserYouTubeCookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_file', models.FileField(help_text='Upload file cookie từ trình duyệt để tránh bị YouTube chặn', upload_to='music/user_cookies/', verbose_name='Cookie File')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_cookie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'YouTube Cookie của User',
                'verbose_name_plural': 'YouTube Cookies của Users',
            },
        ),
    ]
